name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.17]
        mongodb-version: [4.4]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run tests
      run: go test -race ./...
